### ISSUE TITLE
ACI modules for Ansible exist

### ISSUE THREAD

**Issue by dagwieers** [pipoe2h/VMworld-2017#1]
Did you look at the existing ACI modules for Ansible ? https://github.com/datacenter/aci-ansible

We also have a much more convenient **aci_rest** modules, instead of using **uri**.

There's also a very convenient way of managing your ACI infrastructure using the **datacenter.aci-model** role:
 https://galaxy.ansible.com/datacenter/aci-model/

**Comment by pipoe2h** [comment]
Hi Dag,

Thanks for the comment. I was aware of the ACI modules for Ansible with the new version 2.4, but they weren't there before and the idea of this approach is how any infrastructure component with an API can be easily automated using the URI core module and empower the network engineers to develop their own automation.

Regards,
Jose Gomez

**Comment by dagwieers** [comment]
Right. The ACI modules existed since 2015, but granted they were not perfect. They have been improved only recently.

Using the **uri** module you don't have login-support, idempotency, error detection and check-mode/diff support.

So to me that's not a viable solution, but rather a last resort if nothing better exists. And even then, creating your own module is probably better/easier than having the complexity in your playbook.

**Comment by pipoe2h** [comment]
Like you said, the modules from 2015 didn't cover all the ACI components and they were acquired by Cisco around 6 months ago. Since then Cisco has improved them until what we have right now with Ansible 2.4

About the missing features with URI, I disagree. I have all the ones you have mentioned. They weren't covered on this session. 

If you have seen the video from the VMworld session, I mentioned the ideal way to go is with modules, but it requires Python skills and the purpose for this session was to demonstrate everyone can do automation. The next step on the evolution is to get Python skills and develop your own modules like you pointed.
